### ISSUE TITLE
Todo list for FakeHN

### ISSUE THREAD

**Issue by hasan5afari** [hasan5afari/FakeHN#1]
Complete list of tasks .
List items are sorted by their priority .

- [ ] Authorization system
- [ ] Error handling system
- [ ] User management system
- [ ] User profile
- [ ] Search system ( Both for users and posts )
